[versions]
kotlin = "1.7.0"
dokka = "1.7.0"
kotlinCoroutines = "1.6.3"
idea = "211.7628.21" # Android Studio Bumblebee (see https://plugins.jetbrains.com/docs/intellij/android-studio-releases-list.html)
androidxSqlite = "2.2.0"
schemaCrawler = "16.16.18"
stately = "1.2.3"
sqliter = "1.1.2"
testhelp = "0.6.3"
sqljs = "1.6.2"
paging3 = "3.1.1"
ktlint = "0.43.0"
test = "1.4.0"
agp = "7.2.1"
compileSdk = "31"
minSdk = "14"
sqlPsi = "0.4.2"

[libraries]
kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
kotlin-test-commonAnnotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-test-js = { module = "org.jetbrains.kotlin:kotlin-test-js", version.ref = "kotlin" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlin-coroutines-reactive = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive", version.ref = "kotlinCoroutines" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

androidx-test-core = { module = "androidx.test:core", version.ref = "test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "test" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "androidxSqlite" }
androidx-sqliteFramework = { module = "androidx.sqlite:sqlite-framework", version.ref = "androidxSqlite" }
androidx-paging3-common = { module = "androidx.paging:paging-common", version.ref = "paging3" }
androidx-paging3-rx3 = { module = "androidx.paging:paging-rxjava3", version.ref = "paging3" }
androidx-recyclerView = { module = "androidx.recyclerview:recyclerview", version = "1.2.1" }
android-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }

kotlinPoet = { module = "com.squareup:kotlinpoet", version = "1.12.0" }
junit = { module = "junit:junit", version = "4.13.2" }
jgrapht = { module = "org.jgrapht:jgrapht-core", version = "1.5.1" }
truth = { module = "com.google.truth:truth", version = "1.1.3" }
turbine = { module = "app.cash.turbine:turbine", version = "0.8.0" }
bugsnag = { module = "com.bugsnag:bugsnag", version = "3.6.3" }
picnic = { module = "com.jakewharton.picnic:picnic", version = "0.6.0" }
moshi = { module = "com.squareup.moshi:moshi", version = "1.13.0" }
moshiCodegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version = "1.13.0" }

intellij-java = { module = "com.jetbrains.intellij.java:java-psi", version.ref = "idea" }
intellij-core = { module = "com.jetbrains.intellij.platform:core-impl", version.ref = "idea" }
intellij-core-ui = { module = "com.jetbrains.intellij.platform:core-ui", version.ref = "idea" }
intellij-lang = { module = "com.jetbrains.intellij.platform:lang-impl", version.ref = "idea" }
intellij-testFramework = { module = "com.jetbrains.intellij.platform:test-framework", version.ref = "idea" }
intellij-analysis = { module = "com.jetbrains.intellij.platform:analysis", version.ref = "idea" }

sqlPsi = { module = "com.alecstrong.sql.psi:core", version.ref = "sqlPsi" }
sqlPsiTestFixtures  = { module = "com.alecstrong.sql.psi:test-fixtures", version.ref = "sqlPsi" }
robolectric = { module = "org.robolectric:robolectric", version = "4.8.1" }
rxJava2 = { module = "io.reactivex.rxjava2:rxjava", version = "2.2.21" }
rxJava3 = { module = "io.reactivex.rxjava3:rxjava", version = "3.1.5" }
sqliteJdbc = { module = "org.xerial:sqlite-jdbc", version = "3.36.0.3" }
postgresJdbc = { module = "org.postgresql:postgresql", version = "42.4.0" }
mysqlJdbc = { module = "mysql:mysql-connector-java", version = "8.0.29" }

schemaCrawler-tools = { module = "us.fatehi:schemacrawler-tools", version.ref = "schemaCrawler" }
schemaCrawler-sqlite = { module = "us.fatehi:schemacrawler-sqlite", version.ref = "schemaCrawler" }

objectDiff = { module = "de.danielbechler:java-object-diff", version = "0.95" }
sqliter = { module = "co.touchlab:sqliter-driver", version.ref = "sqliter" }
stately-core = { module = "co.touchlab:stately-common", version.ref = "stately" }
stately-concurrency = { module = "co.touchlab:stately-concurrency", version.ref = "stately" }
stately-collections = { module = "co.touchlab:stately-collections", version.ref = "stately" }

testhelp = { module = "co.touchlab:testhelp", version.ref = "testhelp" }
burst = { module = "com.squareup.burst:burst-junit4", version = "1.2.0" }
testParameterInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version = "1.8" }

r2dbc = { module = "io.r2dbc:r2dbc-spi", version = "1.0.0.RELEASE" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-native-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-js = { id = "org.jetbrains.kotlin.js", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
intellij = { id = "org.jetbrains.intellij", version = "1.6.0" }
grammarKitComposer = { id = "com.alecstrong.grammar.kit.composer", version = "0.1.10" }
publish = { id = "com.vanniktech.maven.publish", version = "0.20.0" }
spotless = { id = "com.diffplug.spotless", version = "6.7.2" } # When updating, check if we can remove base plugin from root build.gradle
changelog = { id = "org.jetbrains.changelog", version = "1.3.1" }
shadow = { id = "com.github.johnrengelman.shadow", version = "7.1.2" }
ksp = { id = "com.google.devtools.ksp", version = "1.7.0-1.0.6" }
